pg_version = "16"
excluded_rules = [
    "prefer-text-field",
    "prefer-bigint-over-int",
    "prefer-timestamp-tz",
    "prefer-robust-stmts",
    "ban-char-field",
    "require-timeout-settings",
    "require-concurrent-index-creation",
]
