apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-genai-config
  labels:
    {{- include "t99-app.labels" . | nindent 4 }}
data:
  AUTH_JWKS_URI: http://{{ .Release.Name }}-auth:3000/api/auth/jwks
  AUTH_ISSUER: https://{{ .Values.domain }}
  LLM_BASE_URL: https://logos.aet.cit.tum.de:8080/v1
  LLM_MODEL: openai/gpt-oss-120b
