apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-swagger-ui
  labels:
    {{- include "t99-app.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      name: http
  selector:
    {{- include "t99-app.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: swagger-ui
