apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: stage
  namespace: t99
  annotations:
    kargo.akuity.io/auto-promote: 'true'
spec:
  requestedFreight:
    - origin:
        kind: Warehouse
        name: t99-app-warehouse
      sources:
        direct: true
  promotionTemplate:
    spec:
      steps:
        - uses: git-clone
          config:
            repoURL: https://github.com/aet-devops26/team-99-downtime
            checkout:
              - branch: main
                path: ./repo
        - uses: yaml-update
          config:
            path: ./repo/k8s/helm/t99-app/values.stage.yaml
            updates:
              - key: authService.image.tag
                value: ${{ imageFrom("ghcr.io/aet-devops26/team-99-downtime/t99-auth-service").Tag }}
              - key: client.image.tag
                value: ${{ imageFrom("ghcr.io/aet-devops26/team-99-downtime/t99-client").Tag }}
              - key: transactionService.image.tag
                value: ${{ imageFrom("ghcr.io/aet-devops26/team-99-downtime/t99-transaction-service").Tag }}
              - key: notificationService.image.tag
                value: ${{ imageFrom("ghcr.io/aet-devops26/team-99-downtime/t99-notification-service").Tag }}
              - key: budgetService.image.tag
                value: ${{ imageFrom("ghcr.io/aet-devops26/team-99-downtime/t99-budget-service").Tag }}
              - key: genaiService.image.tag
                value: ${{ imageFrom("ghcr.io/aet-devops26/team-99-downtime/t99-genai-service").Tag }}
        - uses: git-commit
          as: commit
          config:
            path: ./repo
            messageTemplate: 'chore(kargo): promote t99-stage to {{ .Freight.ID }}'
        - uses: git-push
          config:
            path: ./repo
            targetBranch: main
        - uses: argocd-update
          config:
            apps:
              - name: t99-stage
                sources:
                  - repoURL: https://github.com/aet-devops26/team-99-downtime
                    desiredCommit: ${{ outputs.commit.commit }}
