apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: t99-app-warehouse
  namespace: t99
spec:
  subscriptions:
    - image:
        repoURL: ghcr.io/aet-devops26/team-99-downtime/t99-auth-service
        semverConstraint: '>=0.1.0'
        discoveryLimit: 5
    - image:
        repoURL: ghcr.io/aet-devops26/team-99-downtime/t99-client
        semverConstraint: '>=0.1.0'
        discoveryLimit: 5
    - image:
        repoURL: ghcr.io/aet-devops26/team-99-downtime/t99-transaction-service
        semverConstraint: '>=0.1.0'
        discoveryLimit: 5
    - image:
        repoURL: ghcr.io/aet-devops26/team-99-downtime/t99-notification-service
        semverConstraint: '>=0.1.0'
        discoveryLimit: 5
    - image:
        repoURL: ghcr.io/aet-devops26/team-99-downtime/t99-budget-service
        semverConstraint: '>=0.1.0'
        discoveryLimit: 5
    - image:
        repoURL: ghcr.io/aet-devops26/team-99-downtime/t99-genai-service
        semverConstraint: '>=0.1.0'
        discoveryLimit: 5
