#!/usr/bin/env bun
export {};

// For the direct Helm deploy path (cd.yml), no manual bootstrap is needed:
//   - DB password and JWT key are generated by Helm on first deploy (lookup pattern)
//   - GHCR pull secret is created by the CD workflow using GITHUB_TOKEN
//
// For the ArgoCD + Kargo path, run: bun run scripts/bootstrap-argocd-kargo.ts

console.log('Nothing to bootstrap for the direct Helm deploy path.');
console.log('Secrets are created automatically on first deploy via GitHub Actions.');
console.log('\nFor ArgoCD + Kargo: bun run scripts/bootstrap-argocd-kargo.ts');
