apiVersion: v1
kind: Service
metadata:
  name: mailhog
  namespace: monitoring
  labels:
    app.kubernetes.io/name: mailhog
    app.kubernetes.io/part-of: t99-observability
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: mailhog
  ports:
    - name: smtp
      port: 1025
      targetPort: 1025
      protocol: TCP
    - name: http
      port: 8025
      targetPort: 8025
      protocol: TCP
