{{- $dbSecret := lookup "v1" "Secret" .Release.Namespace "t99-db-credentials" -}}
apiVersion: v1
kind: Secret
metadata:
  name: t99-db-credentials
  labels:
    {{- include "t99-app.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
type: Opaque
data:
  {{- if and $dbSecret $dbSecret.data }}
  password: {{ index $dbSecret.data "password" }}
  {{- else }}
  password: {{ randAlphaNum 32 | b64enc }}
  {{- end }}
---
{{- $appSecret := lookup "v1" "Secret" .Release.Namespace "t99-app-secrets" }}
apiVersion: v1
kind: Secret
metadata:
  name: t99-app-secrets
  labels:
    {{- include "t99-app.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
type: Opaque
data:
  {{- if and $appSecret $appSecret.data }}
  jwtSigningKey: {{ index $appSecret.data "jwtSigningKey" }}
  {{- else }}
  jwtSigningKey: {{ randAlphaNum 64 | b64enc }}
  {{- end }}
