name: CI Pipeline

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    name: Build, Test, and Publish Containers

    permissions:
      contents: read
      # Required permissions for uploading to ghcr.io
      packages: write
      id-token: write
      # Required for publishing test results
      issues: read
      checks: write
      pull-requests: write

    env:
      NX_KEY: ${{ secrets.NX_KEY }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0 # Required for Nx affected logic
          filter: tree:0 # Optional, but recommended by nx

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      # install python uv
      - name: Install uv (Python Package & Version Manager)
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b

      - name: Derive appropriate SHAs for base and head for nx affected
        uses: nrwl/nx-set-shas@v5

      - name: Restore Nx Cache
        uses: actions/cache/restore@v5
        id: cache-restore
        with:
          path: .nx/cache
          # Key includes the OS and a hash of your lockfile.
          # We add the Run ID so it always creates a fresh entry for the next run.
          key:
            nx-shared-${{ runner.os }}-${{ hashFiles('bun.lock') }}-${{ github.run_id }}
            # Restore-keys allow it to find the MOST RECENT cache if an exact match isn't found.
          restore-keys: |
            nx-shared-${{ runner.os }}-${{ hashFiles('bun.lock') }}-
            nx-shared-${{ runner.os }}-

      - name: Install Dependencies
        run: bun install --frozen-lockfile

      # Run affected tests across React, Python, and Spring Boot
      - name: Run Tests
        run: bun nx affected --target=test --parallel=3
        continue-on-error: true

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        # Run even if tests failed to ensure results are published
        if: (!cancelled())
        with:
          files: |
            **/reports/**/*.xml
            **/target/surefire-reports/*.xml
            **/build/test-results/**/*.xml
          check_name: "Test Results"
          comment_mode: "changes"

      # Run affected builds
      - name: Run Build
        run: bun nx affected --target=build --parallel=3

      # This step runs even if the steps above fails
      - name: Save Nx Cache
        uses: actions/cache/save@v5
        if: always() && steps.cache-restore.outputs.cache-hit != 'true'
        with:
          path: .nx/cache
          key: ${{ steps.cache-restore.outputs.cache-primary-key }}

      - name: Log in to GHCR
        # Only run on success and merges to main
        #&& github.event_name == 'push'
        if: success()
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        # && github.event_name == 'push'
        if: success()
        uses: docker/setup-buildx-action@v3

      # Build and Push Containers (Runs on the local GitHub runner)
      - name: Build & Push Containers
        # Only push on success and merges to main
        #&& github.event_name == 'push'
        if: success()
        run: bun nx affected --target=docker:build  -- --push
