name: Docker Build and Publish Pipeline

on:
  push:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    name: Docker Build & Publish Affected Containers

    permissions:
      contents: read
      # Required permissions for uploading to ghcr.io
      packages: write
      id-token: write

    env:
      NX_KEY: ${{ secrets.NX_KEY }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0 # Required for Nx affected logic
          filter: tree:0 # Optional, but recommended by nx

      - name: Setup Build Tools
        uses: ./.github/actions/setup-gradle-env

      - name: Derive appropriate SHAs for base and head for nx affected
        uses: nrwl/nx-set-shas@v5

      - name: Restore Nx Cache
        uses: actions/cache/restore@v5
        id: cache-restore
        with:
          path: .nx/cache
          # Key includes the OS and a hash of your lockfile.
          # We add the Run ID so it always creates a fresh entry for the next run.
          key:
            nx-shared-${{ runner.os }}-${{ hashFiles('bun.lock') }}-${{ github.run_id }}
            # Restore-keys allow it to find the MOST RECENT cache if an exact match isn't found.
          restore-keys: |
            nx-shared-${{ runner.os }}-${{ hashFiles('bun.lock') }}-
            nx-shared-${{ runner.os }}-

      # Run affected builds
      - name: Run Build
        run: bun nx affected --target=build --parallel=3

      # This step runs even if the steps above fails
      - name: Save Nx Cache
        uses: actions/cache/save@v5
        if: always() && steps.cache-restore.outputs.cache-hit != 'true'
        with:
          path: .nx/cache
          key: ${{ steps.cache-restore.outputs.cache-primary-key }}

      # Login to GitHub Container Registry
      - name: Log in to GHCR
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Build Containers
      - name: Build Containers
        run: bun nx affected --target=docker:build

      # Publish Containers
      - name: Publish Containers
        run: bun nx release --dockerVersionScheme=production --first-release
