name: Lint

on:
  pull_request:
  merge_group:

jobs:
  lint:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0 # Required for Nx affected logic
          filter: tree:0 # Optional, but recommended by nx

      - name: Setup Build Tools
        uses: ./.github/actions/setup-build-tools

      - name: Lint changed files
        run: bunx lint-staged --diff="origin/${{ github.base_ref }}...HEAD" --config config/lint-staged.config.mjs

      - name: Fail if linters left uncommitted changes
        run: git diff --exit-code
